create table app_users (
    id varchar(36) primary key,
    display_name varchar(40) not null,
    phone_number varchar(20) not null unique,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table order_posts (
    id varchar(36) primary key,
    owner_user_id varchar(36) not null,
    store_name varchar(80) not null,
    latitude double precision not null,
    longitude double precision not null,
    address_hint varchar(100) not null,
    expected_delivery_time timestamp not null,
    minimum_order_amount numeric(10, 2) not null,
    current_cart_amount numeric(10, 2) not null,
    post_radius_miles integer not null,
    title varchar(120) not null,
    notes varchar(300) not null,
    masked_phone varchar(20) not null,
    phone_number varchar(20) not null,
    phone_reveal_enabled boolean not null,
    interested_count integer not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_order_posts_owner foreign key (owner_user_id) references app_users (id)
);

create table post_interests (
    id bigint generated by default as identity primary key,
    post_id varchar(36) not null,
    user_id varchar(36) not null,
    created_at timestamp not null,
    constraint fk_post_interests_post foreign key (post_id) references order_posts (id),
    constraint fk_post_interests_user foreign key (user_id) references app_users (id),
    constraint uk_post_interest_unique unique (post_id, user_id)
);

create table chat_messages (
    id bigint generated by default as identity primary key,
    post_id varchar(36) not null,
    sender_user_id varchar(36) not null,
    sender_alias varchar(40) not null,
    text varchar(300) not null,
    sent_at timestamp not null,
    constraint fk_chat_messages_post foreign key (post_id) references order_posts (id),
    constraint fk_chat_messages_sender foreign key (sender_user_id) references app_users (id)
);

create table otp_codes (
    id bigint generated by default as identity primary key,
    phone_number varchar(20) not null,
    code_hash varchar(128) not null,
    expires_at timestamp not null,
    used boolean not null,
    created_at timestamp not null
);

create table auth_sessions (
    id bigint generated by default as identity primary key,
    user_id varchar(36) not null,
    token_hash varchar(128) not null unique,
    expires_at timestamp not null,
    revoked boolean not null,
    created_at timestamp not null,
    revoked_at timestamp,
    constraint fk_auth_sessions_user foreign key (user_id) references app_users (id)
);

create index idx_order_posts_created_at on order_posts (created_at);
create index idx_post_interests_user_id on post_interests (user_id);
create index idx_chat_messages_post_id on chat_messages (post_id);
create index idx_otp_codes_phone_created on otp_codes (phone_number, created_at desc);
create index idx_auth_sessions_token_hash on auth_sessions (token_hash);
